### ISSUE TITLE
Testing Bug: Unable to connect to AppDataSource

### ISSUE THREAD

**Issue by aiillssa** [aiillssa/Husky-Hustler-Backend#13]
When testing, if there are issues connecting to the AppDataSource, make sure that any `before` and `after` hooks are inside the `describe` block! Make sure it is before the `it`! Additionally, make sure we initialize the AppDataSource using `AppDataSource.initialize()` in the before hook, and then destroy the connection with `AppDataSource.destroy()`

**Comment by Sean0z** [comment]
solved
