### ISSUE TITLE
Failed to create a business

### ISSUE THREAD

**Issue by planetquack1** [aiillssa/Husky-Hustler-Backend#19]
Adding a new business returns an error: 
[Controller - createShop] failed trying to access Shops table
Error: QueryFailedError: Error: Cannot insert duplicate key row in object 'dbo.shops' with unique index 'REL_3b4ce1fd90127dc698bf391e87'. The duplicate key value is (18).

**Comment by Sean0z** [comment]
This error is referring to a feature where you cannot have more than one shop per user. This is our intended implementation, and we have since added a clear error message on the addBusinessPage to convey this to users when they try to create more than one shop

**Comment by Sean0z** [comment]
Also at the time of our beta demo the owner of the user was hard coded to be the same person every time which is why new users could not create shops. We have since changed the owner to be whoever is logged in, so new users can create a shop if they don't already have one.
