### ISSUE TITLE
Backend README file can have clearer instructions

### ISSUE THREAD

**Issue by yyu2022-uw** [aiillssa/Husky-Hustler-Backend#21]
In the README.md file, it would be helpful to include instructions on how to run the backend (e.g., npm run dev), similar to the instructions already provided in the frontend README.md.

Additionally, while there is a link to all the documentation, it’s not clear which document is specific to the backend. Maybe consider renaming "Developer Documentation" to "Backend Documentation" (similar to how the frontend document is named "Frontend Documentation"). This would make it easier for readers to identify and navigate the documentation.

**Comment by Sean0z** [comment]
Thanks for the feedback! We edited our readme and wiki with this feedback in mind to make everything clearer.
