### ISSUE TITLE
Testing Bug: Tests allowing incorrectly formatted data to be added

### ISSUE THREAD

**Issue by aiillssa** [aiillssa/Husky-Hustler-Backend#6]
1. Make sure to initialize the AppDataSource like `AppDataSource.initialize()` before running tests within the it chunk
2. Since we have validators/middleware, you can't just call the method to test! We have to call the validator, and then pass in whatever method as the nextFunction:
`createUserValidator(s,s2,() => createUser(s,s2));`

**Comment by Sean0z** [comment]
Not a bug anymore
